---
self-hosted-runner:
  # Labels of self-hosted runner in array of string
  labels:
  - gcp-core-2-release
  - gcp-core-4-release
  - gcp-core-8-release
  - gcp-core-16-release
  - gcp-core-32-release
  - gcp-core-2-longrunning
  - gcp-core-4-longrunning
  - gcp-core-8-longrunning
  - gcp-core-16-longrunning
  - gcp-core-32-longrunning
  - gcp-core-2-default
  - gcp-core-4-default
  - n1-standard-32-netssd-preempt
  - n1-standard-16-netssd-preempt
  - n1-standard-8-netssd-preempt
  - n1-standard-8-netssd-preempt-quick
