---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files

- repo: https://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
  hooks:
  - id: shell-lint
    args: [--external-sources]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.1
  hooks:
  - id: actionlint

- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 37.399.0
  hooks:
  - id: renovate-config-validator
    args: ["--strict"]
