---
default_language_version:
  node: lts
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files

- repo: https://github.com/detailyang/pre-commit-shell
  rev: v1.0.6
  hooks:
    - id: shell-lint
      args: [--external-sources]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.4
  hooks:
    - id: actionlint
      args: ["-config-file", "actionlint/actionlint.yaml"]

- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 39.57.1
  hooks:
  - id: renovate-config-validator
    args: ["--strict"]
    language_version: 20.18.0 # temporary workaround to mitigate issue https://github.com/renovatebot/pre-commit-hooks/issues/2460
