---
name: Deploy preview environment

description: Deploys a preview environment.

inputs:

  revision:
    description: Revision or branch of the Helm chart. Typically the branch to be deployed, or `master`.
    required: true

  app_name:
    description: The name of the argocd application, generally "product-deployment_id".
    required: true

  app_url:
    description: The URL to access the deployed app.
    required: true

  argocd_server:
    description: URL of the Argo CD instance to target.
    required: false
    default: argocd.int.camunda.com

  argocd_token:
    description: An Argo CD token with sufficient permissions to create Applications.
    required: true

  argocd_version:
    # renovate: datasource=docker depName=quay.io/argoproj/argocd
    default: v2.8.4
    description: Version tag of Argo CD CLI tool
    required: false

  argocd_arguments:
    description: List of arguments to pass to Argocd command for creating the new application
    required: true
runs:
  using: composite
  steps:
  - name: Restore cache
    uses: actions/cache@v3
    id: tool-cache-argocd
    with:
      path: /usr/local/bin/argocd
      key: ${{ runner.os }}-tool-cache-argo-${{ inputs.argocd_version }}
  - name: Setup Argo CD
    shell: bash
    if: ${{ steps.tool-cache-argocd.outputs.cache-hit != 'true' }}
    run: |-
      curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${{ inputs.argocd_version }}/argocd-linux-amd64
      chmod +x /usr/local/bin/argocd
      argocd version
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server }}
    #########################################################################
    # Create a GitHub deployment that points to the URL we're going to deploy to.
    # If a Pull Request exists, it will show the status of this deployment.
  - uses: bobheadxi/deployments@v1.4.0
    name: Create GitHub deployment
    id: deployment
    with:
      step: start
      token: "${{ github.token }}"
      env: ${{ inputs.app_name }}
      ref: ${{ inputs.revision }}
  - name: Deploy
    shell: bash
    run: >-
      argocd app create ${{ inputs.argocd_arguments }}

      argocd app sync ${{ inputs.app_name }} --async --force || true
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server }}
  - name: Wait for sync (up to 20 minutes)
    shell: bash
    run: |-
      echo "::group::wait for sync"
      # Wait for the ArgoCD app to reach a synced and healthy state
      # Retry if error code = PermissionDenied, as this may be a consistency problem
      i=1
      until \
        error=$(argocd app wait ${{ inputs.app_name }} --timeout 1200 --health 3>&2 2>&1 1>&3);
      do
        error_code=$?
        echo "$error" 1>&2
        # Check if PermissionDenied error
        if ! echo "$error" | grep "code = PermissionDenied" > /dev/null; then
          exit $error_code
        fi
        # Exit after 5 attempts
        if [ $i -ge 5 ]; then
          exit $error_code
        fi
        echo "Retry $i ..."
        ((i++))
        sleep 5
      done
      echo "::endgroup::"
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server  }}
    #########################################################################
    # Update the deployment status so we can see the result in the Pull Request
    # or in the list of environments.
  - name: Update branch deployment status
    # `always()` ensures that the deployment status
    # is updated regardless of previous steps failing.
    if: always()
    uses: bobheadxi/deployments@v1.4.0
    with:
      step: finish
      token: ${{ github.token }}
      # If composite action has been cancelled (by a user action, tiemout etc.), we consider it a failure
      # In that case, status must be set/changed explicitly to "failure", otherwise bobheadxi/deployments will define the deployment as inactive.
      status: ${{ github.action_status != 'cancelled' && github.action_status || 'failure'}}
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      env_url: ${{ inputs.app_url }}
      ref: ${{ inputs.revision }}
      env: ${{ inputs.app_name }}
