---
name: Deploy preview environment

description: Deploys a preview environment.

inputs:

  revision:
    description: Revision or branch of the Helm chart. Typically the branch to be deployed, or `master`.
    required: true

  app_name:
    description: The name of the argocd application, generally "product-deployment_id".
    required: true

  app_url:
    description: The URL to access the deployed app.
    required: true

  argocd_server:
    description: URL of the Argo CD instance to target.
    required: false
    default: argocd.int.camunda.com

  argocd_token:
    description: An Argo CD token with sufficient permissions to create Applications.
    required: true

  argocd_version:
    # renovate: datasource=docker depName=quay.io/argoproj/argocd
    default: v2.11.3
    description: Version tag of Argo CD CLI tool
    required: false

  argocd_arguments:
    description: List of arguments to pass to Argocd command for creating the new application
    required: true
runs:
  using: composite
  steps:
  - name: Restore cache
    uses: actions/cache@v4
    id: tool-cache-argocd
    with:
      path: /usr/local/bin/argocd
      key: ${{ runner.os }}-tool-cache-argo-${{ inputs.argocd_version }}
  - name: Setup Argo CD
    shell: bash
    if: ${{ steps.tool-cache-argocd.outputs.cache-hit != 'true' }}
    run: |-
      curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${{ inputs.argocd_version }}/argocd-linux-amd64
      chmod +x /usr/local/bin/argocd
      argocd version
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server }}
    #########################################################################
    # Create a GitHub deployment that points to the URL we're going to deploy to.
    # If a Pull Request exists, it will show the status of this deployment.
  - uses: bobheadxi/deployments@v1.5.0
    name: Create GitHub deployment
    id: deployment
    with:
      step: start
      token: "${{ github.token }}"
      env: ${{ inputs.app_name }}
      ref: ${{ inputs.revision }}
  - name: Deploy
    shell: bash
    run: |
      max_retries=3
      for attempt in $(seq "$max_retries"); do
          argocd app create ${{ inputs.argocd_arguments }}
          if [ $? -eq 0 ]; then
            echo "Creating Argo CD app with name ${{ inputs.app_name }}"
            sleep 10

            # Fetch app information to make sure the app is registered
            app_info=$(argocd app get ${{ inputs.app_name }} --output json 2>/dev/null)
            if [ $? -eq 0 ] && [ -n "$app_info" ]; then
              echo "::group::app info"
              echo "App Info: $app_info"
              echo "::endgroup::"
              echo "Syncing Argo CD app..."

              argocd app sync ${{ inputs.app_name }} --async --force || true
              break
            else
              echo "Attempt $attempt: Failed to get app information. Retrying..."
              continue
            fi
          else
            echo "Argo CD app creation failed on attempt $attempt."
            if [ "$attempt" -eq "$max_retries" ]; then
                echo "Max retries reached. Exiting workflow."
                exit 1
            else
                echo "Attempt $attempt: Retrying in 10 seconds..."
                sleep 10
            fi
          fi
      done
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server }}
  - name: Wait for sync (up to 20 minutes)
    shell: bash
    run: |-
      echo "::group::wait for sync"
      argocd app wait ${{ inputs.app_name }} --timeout 1200 --health
      echo "::endgroup::"
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server  }}
    #########################################################################
    # Update the deployment status so we can see the result in the Pull Request
    # or in the list of environments.
  - name: Update branch deployment status
    # `always()` ensures that the deployment status
    # is updated regardless of previous steps failing.
    if: always()
    uses: bobheadxi/deployments@v1.5.0
    with:
      step: finish
      token: ${{ github.token }}
      # If composite action has been cancelled (by a user action, tiemout etc.), we consider it a failure
      # In that case, status must be set/changed explicitly to "failure", otherwise bobheadxi/deployments will define the deployment as inactive.
      status: ${{ github.action_status != 'cancelled' && github.action_status || 'failure'}}
      deployment_id: ${{ steps.deployment.outputs.deployment_id }}
      env_url: ${{ inputs.app_url }}
      ref: ${{ inputs.revision }}
      env: ${{ inputs.app_name }}
  - name: Create deployment status artifact
    if: always()
    shell: bash
    env:
      APP_NAME: ${{ inputs.app_name }}
      APP_URL: ${{ inputs.app_url }}
      ARGOCD_SERVER: ${{ inputs.argocd_server }}
      REPO: ${{ github.repository }}
      RUN_ID: ${{ github.run_id }}
    run: |
      template=$(envsubst < ${{ github.action_path }}/comment_template_${{ github.action_status }}.md)
      echo "$template" > status_${{ inputs.app_name }}.md
      echo "$template" >> $GITHUB_STEP_SUMMARY
  - name: Upload deployment status as artifact
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: deployment-status-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.app_name }}
      path: status_${{ inputs.app_name }}.md
      retention-days: 1
