name: DC Upload artifacts
author: Chaima Mansouri
description: Upload artifacts to Camunda download center
inputs:
  gcp_credentials:
    description: JSON key to access the GCP bucket
    required: true
  ee:
    description: The artifact is an enterprise release (set to 'true' if it an enterprise release)
    default: 'false'
    required: false
  env:
    description: The environment that the artifact will be uploded to (possible answers are prod, stage or dev)
    required: false
    default: 'prod'
  version:
    description: Artifact version
    required: false # version is not required since we have similar cases https://downloads.camunda.cloud/release/camunda-modeler/nightly/
  sub_version:
    description: Artifact sub version
    required: false
  artifact_subpath:
    description: In case the path longer than expected
    required: false
  artifact_file:
    description: Artifact(s) to upload. E.g. can contain a wildcard (*) or space separated string
    required: true


runs:
  using: "composite"

  steps:
  - name: Resolve variables
    shell: bash
    id: variables
    run: |
      # resolve bucket name
      if [[ "${{inputs.ee}}" == 'true' ]]; then
         if [[ "${{inputs.env}}" == 'prod' ]]; then
           bucket_name="downloads-camunda-cloud-enterprise-release"
         else
           bucket_name="${{inputs.env}}-downloads-camunda-cloud-enterprise-release"
         fi
      else
         if [[ "${{inputs.env}}" == 'prod' ]]; then
           bucket_name="downloads-camunda-cloud-release"
         else
           bucket_name="${{inputs.env}}-downloads-camunda-cloud-release"
         fi
      fi
      
      echo "bucket_name=${bucket_name}" >> "$GITHUB_OUTPUT"

      # resolve path
      subversion=''
      if [[ "${{inputs.sub_version}}" != '' ]]; then
        subversion="$(echo ${{inputs.sub_version}}/)"
      fi
      echo "subversion=${subversion}" >> "$GITHUB_OUTPUT"

      subpath=''
      if [[ "${{inputs.artifact_subpath}}" != '' ]]; then
        subpath=$(echo ${{inputs.artifact_subpath}}/)        
      fi
      echo "subpath=${subpath}" >> "$GITHUB_OUTPUT"

      version=''
      if [[ "${{inputs.version}}" != '' ]]; then
         version="$(echo ${{inputs.version}}/)"
      fi
      echo "version=${version}" >> "$GITHUB_OUTPUT"
      
      # DC main repository
      dc_repo="$(echo ${{github.repository}} | cut -d'/' -f2)"
      echo "dc_repo=${dc_repo}" >> "$GITHUB_OUTPUT"

  - name: set up gcloud
    uses: google-github-actions/setup-gcloud@v1.1.0

  - name: Upload file
    shell: bash
    run: |
      echo -n ${{ inputs.gcp_credentials }} | base64 -d > key-file.json
      gcloud auth activate-service-account --key-file=key-file.json

      gsutil -m cp ${{ inputs.artifact_file }} gs://${{ steps.variables.outputs.bucket_name }}/${{ steps.variables.outputs.dc_repo }}/${{ steps.variables.outputs.subpath }}${{ steps.variables.outputs.version }}${{ steps.variables.outputs.subversion }}

  - name: Post
    shell: bash
    run: |
      rm -f key-file.json

branding:
  icon: upload
  color: orange
