---
name: Destroy preview environment

description: Destroy preview environment.

inputs:
  app_name:
    description: Argocd app name to be deleted.
    required: true

  revision:
    description: Revision or branch of the Helm chart. Typically the branch to be deployed, or `master`.
    required: true

  argocd_server:
    description: URL of the Argo CD instance to target.
    required: false
    default: argocd.int.camunda.com

  argocd_token:
    description: An Argo CD token with sufficient permissions to create Applications.
    required: true

  argocd_version:
    # renovate: datasource=docker depName=quay.io/argoproj/argocd
    default: v2.13.1
    description: Version tag of Argo CD CLI tool
    required: false
runs:
  using: composite
  steps:
  - name: Restore cache
    uses: actions/cache@v4
    id: tool-cache-argocd
    with:
      path: /usr/local/bin/argocd
      key: ${{ runner.os }}-tool-cache-argo-${{ inputs.argocd_version }}
  - name: Setup Argo CD
    shell: bash
    if: ${{ steps.tool-cache-argocd.outputs.cache-hit != 'true' }}
    run: |-
      curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/${{ inputs.argocd_version }}/argocd-linux-amd64
      chmod +x /usr/local/bin/argocd
      argocd version
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server }}

  - name: Tear down
    shell: bash
    run: argocd app delete ${{ inputs.app_name }} --yes
    env:
      ARGOCD_AUTH_TOKEN: ${{ inputs.argocd_token }}
      ARGOCD_OPTS: "--grpc-web"
      ARGOCD_SERVER: ${{ inputs.argocd_server  }}

  - uses: bobheadxi/deployments@v1.5.0
    if: always()
    name: Deactivate GitHub Deployment environment
    with:
      step: deactivate-env
      token: "${{ github.token }}"
      env: ${{ inputs.app_name }}
      ref: ${{ inputs.revision }}
