name: fossa info

description: Provides context info required for other FOSSA composite actions.

inputs:
  github-token:
    description: |
      The GitHub token to use for API calls.
    default: ${{ github.token }}

outputs:
  is-pull-request:
    description: |
      True in the context of a pull request, false otherwise.
    value: ${{ steps.info.outputs.is-pull-request }}
  base-ref:
    description: |
      The ref (name) of the base branch in the context of a pull request.
      Empty if not a pull request.
    value: ${{ steps.info.outputs.base-ref }}
  base-revision:
    description: |
      The revision (commit SHA) of the base branch in the context of a pull request.
      Empty if not a pull request.
      Generally used to find (via diff) new license issues introduced by a PR.
    value: ${{ steps.info.outputs.base-revision }}
  base-revision-most-recent-with-scanning-results:
    description: |
      The latest base branch revision (commit SHA) with FOSSA scanning results.
      Useful when the base revision has no scanning results, such as after a manual merge commit that did not trigger a workflow (and so a scan).
      Empty if none found.
    value: ${{ steps.pull-request.outputs.base-ref-with-scanning-results }}
  head-ref:
    description: |
      The HEAD ref (name) of the branch to be analyzed by FOSSA, determined based on the context of the event.
    value: ${{ steps.info.outputs.head-ref }}
  head-revision:
    description: |
      The HEAD revision (commit sha) to be analyzed by FOSSA, determined based on the context of the event.
    value: ${{ steps.info.outputs.head-revision }}
  job-start-time:
    description: |
      The start time of the current running job, in Unix timestamp format.
    value: ${{ steps.job.outputs.start-time }}

runs:
  using: composite
  steps:
  - uses: camunda/infra-global-github-actions/setup-gh-cli@fc80933ffe69fd186048d40d39f25f28fa63cb72
  - name: Get context info
    id: info
    env:
      IS_PULL_REQUEST: ${{ github.event_name == 'pull_request' }}
      BASE_REF: >
        ${{
          github.event_name == 'pull_request' &&
          github.event.pull_request.base.ref ||
          ''
        }}
      BASE_REVISION: >
        ${{
          github.event_name == 'pull_request' &&
          github.event.pull_request.base.sha ||
          ''
        }}
      HEAD_REF: >
        ${{
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.ref ||
          github.ref_name
        }}
      HEAD_REVISION: >
        ${{
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.sha ||
          github.sha
        }}
    run: |
      {
        echo "is-pull-request=${IS_PULL_REQUEST}"
        echo "base-ref=${BASE_REF}"
        echo "base-revision=${BASE_REVISION}"
        echo "head-ref=${HEAD_REF}"
        echo "head-revision=${HEAD_REVISION}"
      } >> $GITHUB_OUTPUT
    shell: bash
  - name: Get job info
    id: job
    env:
      GH_TOKEN: ${{ inputs.github-token }}
      RUN_ID: ${{ github.run_id }}
      RUNNER_NAME: ${{ runner.name }}
    run: |
      # Get jobs for the current run
      jobs=$(
        gh api \
          "/repos/{owner}/{repo}/actions/runs/${RUN_ID}/jobs"
      )
      # Fail if results is empty or not a valid JSON
      if [ -z "$jobs" ] || ! echo "$jobs" | jq empty > /dev/null 2>&1; then
        echo "Retrieving jobs failed or returned invalid JSON." >&2
        exit 1
      fi

      # Get the start time of the current running job (in progress)
      # Safe to use runner.name to uniquely match the in progress job, as a runner (GitHub-managed or ephemeral Self-Hosted) runs only one job at a time.
      started_at_timestamp=$(
        echo "${jobs}" | \
          jq -r \
            --arg runner_name "${RUNNER_NAME}" \
            '.jobs[] | select(.runner_name == $runner_name and .status == "in_progress") | .started_at | fromdate'
      )

      echo "start-time=${started_at_timestamp}" >> $GITHUB_OUTPUT
    shell: bash
  - name: Get Pull-Request info
    if: ${{ steps.info.outputs.is-pull-request == 'true' }}
    id: pull-request
    env:
      BASE_REF: ${{ steps.info.outputs.base-ref }}
      BASE_REVISION: ${{ steps.info.outputs.base-revision }}
      GH_TOKEN: ${{ inputs.github-token }}
      WORKFLOW_NAME: ${{ github.workflow }}
    run: |
      # Check recent commits of the base commit for existing scanning results
      # history depth to search for scanning results
      depth=5

      # Ensure history is available for the base branch up to the specified depth
      git fetch origin "${BASE_REF}" --depth=200
      # If not enough, fetch more
      git rev-parse "${BASE_REVISION}~$((depth-1))" >/dev/null 2>&1 || \
        git fetch origin "${BASE_REF}" --unshallow

      # Check if the base branch or its recent parents have scanning results
      base_ref_with_scanning_results=""
      for i in $(seq 0 $((depth-1))); do
        commit=$(git rev-parse "${BASE_REVISION}~$i" 2>/dev/null || true)
        # Check if a workflow run of "Check Licenses" succeeded for the commit
        if gh run list \
          --limit 1000 \
          --commit "$commit" \
          --json workflowName,conclusion \
          --jq '[.[] | select(.workflowName == "'"$WORKFLOW_NAME"'" and .conclusion == "success")] | any' | grep -q true; then
          if [ "$i" -gt 0 ]; then
             echo "Scanning result found for commit=$commit, which is $i commit(s) behind the base branch/ref."
          fi
          base_ref_with_scanning_results=$commit
          break
        fi
      done
      if [ -z "$base_ref_with_scanning_results" ]; then
        echo "No scan results found for base branch '${BASE_REF}' (revision: ${BASE_REVISION}) or any of its recent ancestors."
        echo "::warning::No commit in the recent history of the base branch has scan results available."
        echo "This likely indicates that recent scans for the base branch have failed and need to be addressed."
        echo "Scan results for the base branch are required to compute a diff and identify license issues introduced by this PR. Without it, license checks will likely fail."
      fi
      echo "base-ref-with-scanning-results=${base_ref_with_scanning_results}" >> $GITHUB_OUTPUT
    shell: bash
