name: 'Retry Failed Job'

description: 'Rerun failed jobs if the workflow has failed.'

inputs:
  github-token:
    description: The token used for authentication to github.
    required: true
  repository-name:
    description: The name of the repository in which the job belongs.
    required: true
    default: ${{github.repository}}
  run-id:
    description: The id of the job run.
    required: true
  repository-owner:
    description: The owner of the github repository.
    required: true
    default: ${{github.repository_owner}}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Retry on Cancel
      shell: bash
      run: |
        echo "github token"
        echo ${{ github.event.client_payload.github-token }}
        
        echo "repo name"
        echo ${{ github.event.client_payload.repository-name }}
        
        echo "run id"
        echo ${{ github.event.client_payload.run-id }}
        echo $GITHUB_RUN_ID
        
        echo "repo owner"
        echo ${{ github.event.client_payload.repository-owner }}       
        
        # Fetch information about the workflow run
        echo "Fetching current workflow run"
        API_URL="https://api.github.com/repos/${{ inputs.repository-name }}/actions/runs/${{ inputs.run-id }}"
        WORKFLOW_RUN=$(curl -s -H "Authorization: Bearer ${{ inputs.github-token }}" $API_URL)
        
        # Rerun failed jobs
        echo "Rerunning failed job"
        RERUN_URL="https://api.github.com/repos/${{ github.repository-owner }}/${{ github.repository-name }}/actions/runs/${{ inputs.run-id }}/rerun-failed-jobs"
        curl -X POST -H "Authorization: Bearer ${{ inputs.github-token }}" $RERUN_URL
