name: 'Retry Failed Job'

description: 'Rerun failed jobs if the workflow has failed.'

inputs:
  github-token:
    description: The token used for authentication to github.
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Retry with api
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run:  |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/rerun

    - name: Retry on Cancel
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
       
        echo "repo name"
        echo $GITHUB_REPOSITORY
        
        echo "run id"
        echo $GITHUB_RUN_ID
        
        echo "repo owner"
        echo $GITHUB_REPOSITORY_OWNER      
        
        echo "Rerunning job" 
        gh run rerun $GITHUB_RUN_ID --failed
