name: 'Retry Failed Job'

description: 'Rerun failed jobs if the workflow has failed.'

inputs:
  github-token:
    description: The token used for authentication to github.
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Retry on Cancel
      shell: bash
      run: |
        echo "github token"
        echo ${{ github.event.client_payload.github-token }}
        echo $GITHUB_TOKEN
        
        echo "repo name"
        echo $GITHUB_REPOSITORY
        
        echo "run id"
        echo $GITHUB_RUN_ID
        
        echo "repo owner"
        echo $GITHUB_REPOSITORY_OWNER      
        
        # Fetch information about the workflow run
        echo "Fetching current workflow run"
        API_URL="https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        WORKFLOW_RUN=$(curl -s -H "Authorization: Bearer ${{ inputs.github-token }}" $API_URL)
        
        # Rerun failed jobs
        echo "Rerunning failed job"
        RERUN_URL="https://api.github.com/repos/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/rerun-failed-jobs"
        curl -X POST -H "Authorization: Bearer ${{ inputs.github-token }}" $RERUN_URL
