---
name: Automerge Pull Requests
description: |
  Automatically merge pull requests.
  The action fetches all open pull requests with a specific label (default: `autorelease: pending`) and merges them.
  The merge method is set to squash to allow a requirement for signed commits on the base branch

inputs:
  github-token:
    description: 'Github token with permissions to modify pull requests, contents and actions'
    required: true
    secret: true
  label:
    description: 'Label to filter pull requests'
    required: false
    default: 'autorelease: pending'

runs:
  using: composite
  steps:
  - name: automerge
    uses: pascalgn/automerge-action@v0.16.4
    env:
      GITHUB_TOKEN: "${{ inputs.github-token }}"
      MERGE_METHOD: squash
      MERGE_LABELS: "${{ inputs.label }}"
