---
name: Automerge Pull Requests
description: |
  Automatically merge pull requests.
  The action fetches all open pull requests with a specific label (default: `automerge`) and merges them.
  The merge method is set to squash to allow a requirement for signed commits on the base branch.
  At the moment, this action does not work with the `workflow_dispatch` event due to some flaws in the third-party action.

inputs:
  github-token:
    description: 'Github token with permissions to modify pull requests, contents and actions'
    required: true
    secret: true
  label:
    description: 'Label to filter pull requests'
    required: false
    default: 'automerge'
  vault-addr:
    description: The Vault URL for fetching secrets
    required: true
  vault-role-id:
    description: The Vault role ID for fetching secrets
    required: true
  vault-secret-id:
    description: The Vault secret ID for fetching secrets
    required: true

runs:
  using: composite
  steps:
  - name: Import Secrets
    id: vault-secrets
    uses: hashicorp/vault-action@v3.0.0
    with:
      url: ${{ inputs.vault-addr }}
      method: approle
      roleId: ${{ inputs.vault-role-id }}
      secretId: ${{ inputs.vault-secret-id }}
      secrets: |
        secret/data/products/infra/ci/infra-releases RELEASES_APP_ID;
        secret/data/products/infra/ci/infra-releases RELEASES_APP_KEY;
  - name: Generate a GitHub token for infra-rerun camunda/infra-global-github-actions
    id: github-token
    uses: actions/create-github-app-token@v1
    with:
      app-id: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_ID }}
      private-key: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_KEY }}
  - name: automerge
    uses: pascalgn/automerge-action@v0.16.4
    env:
      GITHUB_TOKEN: "${{ inputs.github-token }}"
      MERGE_METHOD: "squash"
      MERGE_LABELS: "!no-merge,${{ inputs.label }}"
