---
name: Rerun failed run

description: Retrigger a GitHub Actions workflow run that has failed with a specific error message

inputs:
  run-id:
    description: The id of the workflow run to re-trigger
    required: true
  repository:
    description: The name of the repository to which the workflow run belongs
    required: true
  error-messages:
    description: The error messages to check for in the workflow run logs. The workflow will be rerun only if at least one of the given messages is found in the logs of a failed job.
    required: true
  vault-addr:
    description: The Vault URL for fetching secrets
    required: true
  vault-role-id:
    description: The Vault role ID for fetching secrets
    required: true
  vault-secret-id:
    description: The Vault secret ID for fetching secrets
    required: true
  notify-back-on-error:
    description: |-
      When the error message does not match the expected one,
      re-trigger the workflow with the parameter `notify_back_error_message`.
      Your calling workflow must implement the `notify_back_error_message` parameter
      and forward the error.
      This allows you to capture failures that are not related to a specific error.
    default: "false"

runs:
  using: composite
  steps:
    - name: Import Secrets
      id: vault-secrets
      uses: hashicorp/vault-action@v3.0.0
      with:
        url: ${{ inputs.vault-addr }}
        method: approle
        roleId: ${{ inputs.vault-role-id }}
        secretId: ${{ inputs.vault-secret-id }}
        secrets: |
          secret/data/products/infra/ci/retrigger-gha-workflow RETRIGGER_APP_ID;
          secret/data/products/infra/ci/retrigger-gha-workflow RETRIGGER_APP_KEY;

    - name: Generate a GitHub token
      id: github-token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_ID }}
        private_key: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_KEY }}

    - name: Retrigger run
      env:
        GH_DEBUG: api
        GITHUB_TOKEN: ${{ steps.github-token.outputs.token }}
      shell: bash
      run: |
        error_messages="${{ inputs.error-messages }}"
        result=$(echo "$error_messages" | jq -c -n -R '[inputs | select(length > 0)]')
        echo "result: $result"

        gh workflow run rerun-failed-run.yml -R camunda/infra-global-github-actions --ref=main -F run_id=${{ inputs.run-id }} -F repository=${{ inputs.repository }} -F error_messages="$result" -F notify_back_on_error=${{ inputs.notify-back-on-error }} -F notify_back_git_ref=${{ github.ref_name }}
