---
name: Rerun failed run

description: Retrigger a GitHub Actions workflow run that has failed with a specific error message

inputs:
  run-id:
    description: The id of the workflow run to re-trigger
    required: true
  repository:
    description: The name of the repository to which the workflow run belongs
    required: true
  error-messages:
    description: The error messages to check for in the workflow run logs. Only if the messages are found in the failed jobs of the workflow run will be retriggered
    required: true
  vault-addr:
    description: The Vault URL for fetching secrets
    required: true
  vault-role-id:
    description: The Vault role ID for fetching secrets
    required: true
  vault-secret-id:
    description: The Vault secret ID for fetching secrets
    required: true

runs:
  using: composite
  steps:
    - name: Import Secrets
      id: vault-secrets
      uses: hashicorp/vault-action@v3.0.0
      with:
        url: ${{ inputs.vault-addr }}
        method: approle
        roleId: ${{ inputs.vault-role-id }}
        secretId: ${{ inputs.vault-secret-id }}
        secrets: |
          secret/data/products/infra/ci/retrigger-gha-workflow RETRIGGER_APP_ID;
          secret/data/products/infra/ci/retrigger-gha-workflow RETRIGGER_APP_KEY;

    - name: Generate a GitHub token
      id: github-token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_ID }}
        private_key: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_KEY }}

    - name: Retrigger run
      env:
        GH_DEBUG: api
      shell: bash
      run: |
        echo ${{ steps.github-token.outputs.token }} | gh auth login --with-token
        error_messages="${{ inputs.error-messages }}"
        result="["
        IFS=$'\n'
        for line in $error_messages
        echo "line: $line"
        do
          result+="\"$line\","
        done
        result=$(echo $result | sed '$ s/,$//g')
        result+="]"
        echo "result: $result"
        gh workflow run rerun-failed-run.yml -R camunda/infra-global-github-actions --ref=gh-672 -F run_id=${{ inputs.run-id }} -F repository=${{ inputs.repository }} -F error_messages=$result
