---
name: Manage Release
description: |
  This action manages auto-release handling for the repository.
  Based on the configuration in the release-please-config.json file in conjunction with
  all conventional commits since the last release, it will create a new release PR.
  If the PR itself gets merged, the action will create a new release and tag it.
  The config-filename is required until https://github.com/googleapis/release-please-action/issues/1017 is resolved.
  It's currently not possible to use a file from the filesystem as input for the action.
  As soon as this gets resolved, we can centralize the configuration in the repository and remove the need for the config-filename input.

inputs:
  github-token:
    description: 'Github token with permissions to modify pull requests and contents'
    required: true
    secret: true
  config-filename:
    description: |
      filename of a custom release-please configuration file.
    required: false
    default: '.github/config/release-please-config.json' # TODO: remove once https://github.com/googleapis/release-please-action/issues/1017 is resolved
  manifest-filename:
    description: |
      filename of a custom release-please manifest file.
    required: false
    default: '.github/config/.release-please-manifest.json'
  vault-addr:
    description: The Vault URL for fetching secrets
    required: true
  vault-role-id:
    description: The Vault role ID for fetching secrets
    required: true
  vault-secret-id:
    description: The Vault secret ID for fetching secrets
    required: true

runs:
  using: composite
  steps:
  - name: Import Secrets
    id: vault-secrets
    uses: hashicorp/vault-action@v3.0.0
    with:
      url: ${{ inputs.vault-addr }}
      method: approle
      roleId: ${{ inputs.vault-role-id }}
      secretId: ${{ inputs.vault-secret-id }}
      secrets: |
        secret/data/products/infra/ci/infra-releases RELEASES_APP_ID;
        secret/data/products/infra/ci/infra-releases RELEASES_APP_KEY;
  - name: Generate a GitHub token for infra-rerun camunda/infra-global-github-actions
    id: github-token
    uses: actions/create-github-app-token@v1
    with:
      app-id: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_ID }}
      private-key: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_KEY }}
  - name: config-filename defaulting
    shell: bash
    run: |
      if [ -z "${{ inputs.config-filename }}" ]; then
        echo "config-filename=${{ github.action_path }}/release-please-config.json" >> $GITHUB_ENV
      else
        echo "config-filename=${{ inputs.config-filename }}" >> $GITHUB_ENV
      fi
  - name: Manage Release
    uses: googleapis/release-please-action@v4
    with:
      config-file: ${{ env.config-filename }}
      manifest-file: ${{ inputs.manifest-filename }}
      token: ${{ inputs.github-token }}
