name: fossa create-release and reports

description: Creates FOSSA releases in separate groups, generates attribution and SBOM reports with configurable formats, waits for publication, and sends Slack notifications on timeout

inputs:
  api-key:
    description: The API key to access fossa.com
    required: true
  attribution-release-group-id:
    description: Release group ID for attribution reports
    required: true
  sbom-release-group-id:
    description: Release group ID for SBOM reports
    required: true
  release-number:
    description: Version number of the release to be created
    required: true
  project-id:
    description: Project ID (locator)
    required: true
  branch:
    description: Name of the branch
    required: true
  revision-id:
    description: Git commit hash of the scanned revision
    required: true
  attribution-format:
    description: Format for attribution report (e.g., TXT, HTML)
    required: false
    default: 'TXT'
  sbom-format:
    description: Format for SBOM report (e.g., CYCLONEDX_JSON, SPDX_JSON)
    required: false
    default: 'CYCLONEDX_JSON'
  generate-attribution:
    description: Whether to generate attribution report
    required: false
    default: 'true'
  generate-sbom:
    description: Whether to generate SBOM report
    required: false
    default: 'true'
  dry-run:
    description: 'Enable dry-run mode (print commands without executing)'
    required: false
    default: 'false'
  slack-notify:
    description: 'Send Slack notifications on publication timeout'
    required: false
    default: 'false'
  slack-webhook-infra-alerts:
    description: 'Slack webhook URL for infrastructure alerts'
    required: false

runs:
  using: composite
  steps:
    - name: Create FOSSA releases
      id: create-releases
      env:
        FOSSA_API_KEY: ${{ inputs.api-key }}
        ATTRIBUTION_GROUP_ID: ${{ inputs.attribution-release-group-id }}
        SBOM_GROUP_ID: ${{ inputs.sbom-release-group-id }}
        RELEASE_NUMBER: ${{ inputs.release-number }}
        PROJECT_ID: ${{ inputs.project-id }}
        BRANCH: ${{ inputs.branch }}
        REVISION_ID: ${{ inputs.revision-id }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        set -e

        # Build the locator
        LOCATOR="${PROJECT_ID}\$${REVISION_ID}"
        echo "Locator: ${LOCATOR}"

        # Define arrays for group types and IDs
        GROUP_TYPES=("attribution" "sbom")
        GROUP_IDS=("${ATTRIBUTION_GROUP_ID}" "${SBOM_GROUP_ID}")

        # Create releases
        for i in "${!GROUP_TYPES[@]}"; do
          GROUP_TYPE="${GROUP_TYPES[$i]}"
          GROUP_ID="${GROUP_IDS[$i]}"

          echo "Creating ${GROUP_TYPE} release in group: ${GROUP_ID}"

          # Prepare JSON payload
          JSON_PAYLOAD='{
            "title": "'"${RELEASE_NUMBER}"'",
            "projects": [
              {
                "projectId": "'"${PROJECT_ID}"'",
                "branch": "'"${BRANCH}"'",
                "revisionId": "'"${LOCATOR}"'"
              }
            ]
          }'

          API_URL="https://app.fossa.com/api/project_group/${GROUP_ID}/release"

          # Dry-run mode
          if [ "${DRY_RUN}" = "true" ]; then
            echo "==== DRY-RUN: ${GROUP_TYPE} release ===="
            echo "POST ${API_URL}"
            echo ""
            echo "Headers:"
            echo "  accept: application/json"
            echo "  authorization: Bearer ***"
            echo "  content-type: application/json"
            echo ""
            echo "Body:"
            echo "${JSON_PAYLOAD}" | jq '.'
            echo ""

            # Generate mock release ID
            RELEASE_ID="mock-${GROUP_TYPE}-release-id-12345"
            echo "Mock release ID: ${RELEASE_ID}"
            echo "${GROUP_TYPE}-release-id=${RELEASE_ID}" >> ${GITHUB_OUTPUT}
            echo ""
            continue
          fi

          # See https://docs.fossa.com/reference/createreleasegroupreleases
          HTTP_CODE=$(curl --silent --output ${GROUP_TYPE}_response.json --write-out "%{http_code}" \
            --request POST \
            --header "accept: application/json" \
            --header "authorization: Bearer ${FOSSA_API_KEY}" \
            --header "content-type: application/json" \
            --url "${API_URL}" \
            --data "${JSON_PAYLOAD}")

          if [ "${HTTP_CODE}" != "200" ]; then
            echo "Error: ${GROUP_TYPE} release creation failed with HTTP status ${HTTP_CODE}"
            echo "Response:"
            cat ${GROUP_TYPE}_response.json
            exit 1
          fi

          # Extract release ID from response
          RELEASE_ID=$(jq -r '.id' ${GROUP_TYPE}_response.json)

          if [ -z "${RELEASE_ID}" ] || [ "${RELEASE_ID}" = "null" ]; then
            echo "Error: Failed to extract ${GROUP_TYPE} release ID from response"
            cat ${GROUP_TYPE}_response.json
            exit 1
          fi

          echo "Successfully created ${GROUP_TYPE} release with ID: ${RELEASE_ID}"
          echo "${GROUP_TYPE}-release-id=${RELEASE_ID}" >> ${GITHUB_OUTPUT}

          rm -f ${GROUP_TYPE}_response.json
        done
      shell: bash

    - name: Generate reports
      if: success()
      env:
        FOSSA_API_KEY: ${{ inputs.api-key }}
        ATTRIBUTION_GROUP_ID: ${{ inputs.attribution-release-group-id }}
        SBOM_GROUP_ID: ${{ inputs.sbom-release-group-id }}
        ATTRIBUTION_RELEASE_ID: ${{ steps.create-releases.outputs.attribution-release-id }}
        SBOM_RELEASE_ID: ${{ steps.create-releases.outputs.sbom-release-id }}
        ATTRIBUTION_FORMAT: ${{ inputs.attribution-format }}
        SBOM_FORMAT: ${{ inputs.sbom-format }}
        GENERATE_ATTRIBUTION: ${{ inputs.generate-attribution }}
        GENERATE_SBOM: ${{ inputs.generate-sbom }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        set -e

        # Define arrays for report generation
        REPORT_TYPES=("attribution" "sbom")
        GROUP_IDS=("${ATTRIBUTION_GROUP_ID}" "${SBOM_GROUP_ID}")
        RELEASE_IDS=("${ATTRIBUTION_RELEASE_ID}" "${SBOM_RELEASE_ID}")
        FORMATS=("${ATTRIBUTION_FORMAT}" "${SBOM_FORMAT}")
        GENERATE_FLAGS=("${GENERATE_ATTRIBUTION}" "${GENERATE_SBOM}")

        # Generate reports
        for i in "${!REPORT_TYPES[@]}"; do
          REPORT_TYPE="${REPORT_TYPES[$i]}"
          GROUP_ID="${GROUP_IDS[$i]}"
          RELEASE_ID="${RELEASE_IDS[$i]}"
          FORMAT="${FORMATS[$i]}"
          GENERATE="${GENERATE_FLAGS[$i]}"

          if [ "${GENERATE}" != "true" ]; then
            echo "Skipping ${REPORT_TYPE} report generation (disabled)"
            continue
          fi

          echo "Generating ${REPORT_TYPE} report in format: ${FORMAT}"

          # Build URL with query parameters, enable all options
          # See https://docs.fossa.com/reference/queuereleasegroupattributionreport
          URL="https://app.fossa.com/api/project_group/${GROUP_ID}/release/${RELEASE_ID}/attribution/${FORMAT}"
          URL+="?includeDeepDependencies=true"
          URL+="&includeDirectDependencies=true"
          URL+="&includeLicenseList=true"
          URL+="&includeLicenseScan=true"
          URL+="&includeProjectLicense=true"
          URL+="&includeCopyrightList=true"
          URL+="&includeFileMatches=true"
          URL+="&includeOpenVulnerabilities=true"
          URL+="&includeClosedVulnerabilities=true"
          URL+="&includeDependencySummary=true"
          URL+="&includeLicenseHeaders=true"
          URL+="&isPublishing=true"

          # Dry-run mode
          if [ "${DRY_RUN}" = "true" ]; then
            echo "==== DRY-RUN: ${REPORT_TYPE} report ===="
            echo "POST ${URL}"
            echo ""
            echo "Headers:"
            echo "  accept: application/json"
            echo "  Authorization: Bearer ***"
            echo ""
            echo "Query parameters:"
            echo "  includeDeepDependencies=true"
            echo "  includeDirectDependencies=true"
            echo "  includeLicenseList=true"
            echo "  includeLicenseScan=true"
            echo "  includeProjectLicense=true"
            echo "  includeCopyrightList=true"
            echo "  includeFileMatches=true"
            echo "  includeOpenVulnerabilities=true"
            echo "  includeClosedVulnerabilities=true"
            echo "  includeDependencySummary=true"
            echo "  includeLicenseHeaders=true"
            echo "  isPublishing=true"
            echo ""
            echo "✓ Would generate ${REPORT_TYPE} report in ${FORMAT} format"
            echo ""
            continue
          fi

          HTTP_CODE=$(curl --silent --output ${REPORT_TYPE}-report.txt --write-out "%{http_code}" \
            --request POST \
            --header "accept: application/json" \
            --header "Authorization: Bearer ${FOSSA_API_KEY}" \
            --url "${URL}")

          if [ "${HTTP_CODE}" != "200" ]; then
            echo "Error: ${REPORT_TYPE} API request failed with HTTP status ${HTTP_CODE}"
            echo "Response:"
            cat ${REPORT_TYPE}-report.txt
            exit 1
          fi

          echo "Successfully generated ${REPORT_TYPE} report"
        done
      shell: bash

    - name: Wait for reports to be published
      id: wait-for-publication
      if: success()
      env:
        FOSSA_API_KEY: ${{ inputs.api-key }}
        ATTRIBUTION_GROUP_ID: ${{ inputs.attribution-release-group-id }}
        SBOM_GROUP_ID: ${{ inputs.sbom-release-group-id }}
        ATTRIBUTION_RELEASE_ID: ${{ steps.create-releases.outputs.attribution-release-id }}
        SBOM_RELEASE_ID: ${{ steps.create-releases.outputs.sbom-release-id }}
        ATTRIBUTION_FORMAT: ${{ inputs.attribution-format }}
        SBOM_FORMAT: ${{ inputs.sbom-format }}
        GENERATE_ATTRIBUTION: ${{ inputs.generate-attribution }}
        GENERATE_SBOM: ${{ inputs.generate-sbom }}
        DRY_RUN: ${{ inputs.dry-run }}
      run: |
        set -e

        MAX_WAIT_TIME=60
        POLL_INTERVAL=5

        # poll a release group for publication status
        poll_release() {
          local REPORT_TYPE=$1
          local GROUP_ID=$2
          local RELEASE_ID=$3
          local FORMAT=$4
          local GENERATE=$5

          if [ "${GENERATE}" != "true" ]; then
            echo "${REPORT_TYPE}: Skipping (generation disabled)"
            return 0
          fi

          # Determine expected publishedOnPortal value based on format
          # Format inputs: "TXT" or "CYCLONEDX_JSON"
          # API returns: "attribution_txt" or "cyclonedx_json"
          local EXPECTED_STATUS
          case "${FORMAT}" in
            TXT)
              EXPECTED_STATUS="attribution_txt"
              ;;
            CYCLONEDX_JSON)
              EXPECTED_STATUS="cyclonedx_json"
              ;;
            *)
              echo "⚠️  ${REPORT_TYPE}: Unsupported format '${FORMAT}'"
              echo "⚠️  Supported formats: TXT, CYCLONEDX_JSON"
              return 1
              ;;
          esac

          if [ "${DRY_RUN}" = "true" ]; then
            echo "==== DRY-RUN: ${REPORT_TYPE} publication check ===="
            echo "GET https://app.fossa.com/api/project_group/${GROUP_ID}/releases?count=10&page=1"
            echo ""
            echo "Would poll for release ID: ${RELEASE_ID}"
            echo "Expected publishedOnPortal: ${EXPECTED_STATUS}"
            echo "Max wait time: ${MAX_WAIT_TIME} seconds"
            echo "✓ Would wait for ${REPORT_TYPE} report publication"
            echo ""
            return 0
          fi

          local ELAPSED=0
          local PUBLISHED=false

          echo "${REPORT_TYPE}: Waiting for publication (release ID: ${RELEASE_ID}, expected status: ${EXPECTED_STATUS})..."

          while [ ${ELAPSED} -lt ${MAX_WAIT_TIME} ]; do
            # Query the releases API
            HTTP_CODE=$(curl --silent --output ${REPORT_TYPE}_status.json --write-out "%{http_code}" \
              --request GET \
              --header "accept: application/json" \
              --header "authorization: Bearer ${FOSSA_API_KEY}" \
              --url "https://app.fossa.com/api/project_group/${GROUP_ID}/releases?count=10&page=1")

            if [ "${HTTP_CODE}" != "200" ]; then
              echo "⚠️  ${REPORT_TYPE}: Failed to check status (HTTP ${HTTP_CODE})"
              cat ${REPORT_TYPE}_status.json
              rm -f ${REPORT_TYPE}_status.json
              sleep ${POLL_INTERVAL}
              ELAPSED=$((ELAPSED + POLL_INTERVAL))
              continue
            fi

            # Find our release in the response and check publishedOnPortal
            PUBLISHED_STATUS=$(jq -r ".releases[] | select(.id == ${RELEASE_ID}) | .publishedOnPortal" ${REPORT_TYPE}_status.json)

            if [ -z "${PUBLISHED_STATUS}" ]; then
              echo "⚠️  ${REPORT_TYPE}: Release ${RELEASE_ID} not found in response"
              rm -f ${REPORT_TYPE}_status.json
              sleep ${POLL_INTERVAL}
              ELAPSED=$((ELAPSED + POLL_INTERVAL))
              continue
            fi

            echo "${REPORT_TYPE}: Current status: ${PUBLISHED_STATUS} (elapsed: ${ELAPSED}s)"

            if [ "${PUBLISHED_STATUS}" = "${EXPECTED_STATUS}" ]; then
              echo "✓ ${REPORT_TYPE}: Successfully published!"
              PUBLISHED=true
              rm -f ${REPORT_TYPE}_status.json
              return 0
            elif [ "${PUBLISHED_STATUS}" = "null" ] || [ "${PUBLISHED_STATUS}" = "pending" ]; then
              # Still processing, continue waiting
              rm -f ${REPORT_TYPE}_status.json
              sleep ${POLL_INTERVAL}
              ELAPSED=$((ELAPSED + POLL_INTERVAL))
            else
              # Unexpected status
              echo "⚠️  ${REPORT_TYPE}: Unexpected status '${PUBLISHED_STATUS}' (expected '${EXPECTED_STATUS}')"
              rm -f ${REPORT_TYPE}_status.json
              sleep ${POLL_INTERVAL}
              ELAPSED=$((ELAPSED + POLL_INTERVAL))
            fi
          done

          # Timeout reached
          if [ "${PUBLISHED}" = "false" ]; then
            echo "⚠️  WARNING: ${REPORT_TYPE} report publication timeout after ${MAX_WAIT_TIME} seconds"
            echo "⚠️  Last known status: ${PUBLISHED_STATUS}"
            echo "⚠️  The report may still be processing. Check FOSSA portal manually."
            rm -f ${REPORT_TYPE}_status.json
            return 1
          fi
        }

        # Export function for parallel execution
        export -f poll_release
        export FOSSA_API_KEY MAX_WAIT_TIME POLL_INTERVAL DRY_RUN

        # Poll both reports in parallel using background jobs
        ATTRIBUTION_FAILED=0
        SBOM_FAILED=0

        poll_release "attribution" "${ATTRIBUTION_GROUP_ID}" "${ATTRIBUTION_RELEASE_ID}" "${ATTRIBUTION_FORMAT}" "${GENERATE_ATTRIBUTION}" &
        ATTRIBUTION_PID=$!

        poll_release "sbom" "${SBOM_GROUP_ID}" "${SBOM_RELEASE_ID}" "${SBOM_FORMAT}" "${GENERATE_SBOM}" &
        SBOM_PID=$!

        # Wait for both background jobs and capture their exit codes
        wait ${ATTRIBUTION_PID} || ATTRIBUTION_FAILED=$?
        wait ${SBOM_PID} || SBOM_FAILED=$?

        # Report results
        echo ""
        echo "==== Publication Status Summary ===="
        if [ ${ATTRIBUTION_FAILED} -eq 0 ] && [ "${GENERATE_ATTRIBUTION}" = "true" ]; then
          echo "✓ Attribution report: Published"
        elif [ "${GENERATE_ATTRIBUTION}" = "true" ]; then
          echo "⚠️  Attribution report: Publication timeout (see warnings above)"
        fi

        if [ ${SBOM_FAILED} -eq 0 ] && [ "${GENERATE_SBOM}" = "true" ]; then
          echo "✓ SBOM report: Published"
        elif [ "${GENERATE_SBOM}" = "true" ]; then
          echo "⚠️  SBOM report: Publication timeout (see warnings above)"
        fi

        # Don't fail the workflow if reports timeout, just warn
        if [ ${ATTRIBUTION_FAILED} -ne 0 ] || [ ${SBOM_FAILED} -ne 0 ]; then
          echo ""
          echo "::warning::One or more FOSSA reports did not publish within the timeout period. Notify @infra-medic to check the FOSSA portal manually."
          echo "publication-timeout=true" >> ${GITHUB_OUTPUT}
        else
          echo "publication-timeout=false" >> ${GITHUB_OUTPUT}
        fi

        # Set individual report status outputs
        echo "attribution-published=$([[ ${ATTRIBUTION_FAILED} -eq 0 ]] && echo 'true' || echo 'false')" >> ${GITHUB_OUTPUT}
        echo "sbom-published=$([[ ${SBOM_FAILED} -eq 0 ]] && echo 'true' || echo 'false')" >> ${GITHUB_OUTPUT}

        exit 0
      shell: bash

    - name: Send Slack notification
      if: always() && steps.wait-for-publication.outputs.publication-timeout == 'true' && inputs.slack-notify == 'true'
      uses: slackapi/slack-github-action@v2
      with:
        payload: |
          {
            "text": "⚠️ FOSSA Report Publication Timeout",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "⚠️ FOSSA Report Publication Timeout"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Release:*\n${{ inputs.release-number }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${{ inputs.branch }}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Workflow:*\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Report Status:*\n${{ steps.wait-for-publication.outputs.attribution-published == 'true' && '✓' || '⚠️' }} Attribution Report (${{ inputs.attribution-format }})\n${{ steps.wait-for-publication.outputs.sbom-published == 'true' && '✓' || '⚠️' }} SBOM Report (${{ inputs.sbom-format }})"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "One or more reports did not publish within the timeout period. Please check the FOSSA portal manually:\n• <https://app.fossa.com/projects/project_group/${{ inputs.attribution-release-group-id }}|Attribution Release Group>\n• <https://app.fossa.com/projects/project_group/${{ inputs.sbom-release-group-id }}|SBOM Release Group>\n\nFor manual license report management, check the <https://confluence.camunda.com/spaces/SRE/pages/277024793/FOSSA#FOSSA-LicenseReportManagement|Handbook>."
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "cc: @infra-medic"
                  }
                ]
              }
            ]
          }
        webhook: ${{ inputs.slack-webhook-infra-alerts }}
        webhook-type: incoming-webhook
