---
name: Check for PR conflicts

description: |
  This action checks PRs of a repository for merge conflicts
  and posts a comment to the respective PR if such a conflict exists.
  It also cleans up existing comments, if there's no conflict (e.g. it got resolved)

inputs:
  label-filters:
    default: "deploy-preview"
    description: Comma separated list of PR labels to narrow down the scan.
    required: false
  pull-request-id:
    description: Limits the scan to the given PR-ID
    requried: false

runs:
  using: composite
  steps:
  - name: Scan PRs
    id: inputs
    shell: bash
    env:
      COMMENT_BODY_TEMPLATE_PATH: ${{ github.action_path }}/templates/comment-body.md
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ github.token }}
      LABEL_FILTERS: ${{ inputs.label-filters }}
      PR_ID: ${{ inputs.pull-request-id }}
    run: |
      ${{ github.action_path }}/check-for-conflicts.sh
