---
name: Check Copilot Commits

description: Checks if there are any commits authored by GitHub Copilot in the specified branch or commit range. Optionally checks co-authored commits too.

inputs:
  repository:
    description: 'Repository to check (format: owner/repo)'
    required: true
  branch:
    description: 'Branch to check for copilot commits'
    required: true
  base-branch:
    description: 'Base branch to compare against'
    required: true
    default: 'main'
  github-token:
    description: 'GitHub token for accessing the repository. Required if checking a different repository.'
    required: false
    default: ${{ github.token }}
  check-co-author:
    description: 'Whether to also check for co-authored commits. When false, only checks author field.'
    required: false
    default: 'false'

outputs:
  copilot-commits-found:
    description: "Whether Copilot commits were found (true/false)"
    value: ${{ steps.check.outputs.copilot_commits_found }}
  copilot-commits-hashes:
    description: "Commit hashes of Copilot authored commits (and co-authored if enabled)"
    value: ${{ steps.check.outputs.copilot_commits_hashes }}

runs:
  using: composite
  steps:
  - name: Checkout repository
    uses: actions/checkout@v6
    with:
      repository: ${{ inputs.repository || github.repository }}
      token: ${{ inputs.github-token }}
      fetch-depth: 0

  - name: Check for Copilot commits
    id: check
    shell: bash
    env:
      REPOSITORY: ${{ inputs.repository || github.repository }}
      BRANCH: ${{ inputs.branch || (github.event.pull_request && github.event.pull_request.head.ref) || github.ref_name }}
      BASE_BRANCH: ${{ inputs.base-branch }}
      CHECK_CO_AUTHOR: ${{ inputs.check-co-author }}
      GITHUB_TOKEN: ${{ inputs.github-token }}
    run: ${{ github.action_path }}/check.sh
