---
name: Validate PR Title
description: |
  Validates pull request titles against conventional commit format.
  This action helps ensure that PR titles follow conventional commit standards,
  which is critical for side projects using release-please when using
  "Squash & Merge".

inputs:
  github-token:
    description: 'GitHub token with read access to pull requests'
    required: false
    default: ${{ github.token }}
  types:
    description: |
      List of allowed commit types.
      Defaults to common conventional commit types.
    required: false
    default: |
      feat
      fix
      docs
      style
      refactor
      test
      build
      ci
      chore
      revert
  subject-pattern:
    description: |
      Regex pattern for the subject line.
      Default ensures subject doesn't start with uppercase.
    required: false
    default: '^(?![A-Z]).+$'

runs:
  using: composite
  steps:
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6.0.1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        types: ${{ inputs.types }}
        subjectPattern: ${{ inputs.subject-pattern }}
        validateSingleCommit: true
