name: Configure Pull Request

description: Sets the parameters of an existing Pull Request at once

inputs:
  github-token:
    description: A GitHub access token with write access to the project
    required: true
    type: string
  labels:
    description: Comma-separated list of labels
    required: false
    type: string
  project-url:
    description: URL of a GitHub project
    required: false
    type: string
  reviewers:
    description: Comma-separated list of users
    required: false
    type: string
  team-reviewers:
    description: Comma-separated list of teams
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Set labels
      if: ${{ inputs.labels != '' }}
      uses: buildsville/add-remove-label@v2.0.1
      with:
        labels: ${{ inputs.labels }}
        token: ${{ inputs.github-token }}
        type: add
    - name: Set project
      if: ${{ inputs.project-url != '' }}
      uses: actions/add-to-project@v0.6.0
      with:
        github-token: ${{ inputs.github-token }}
        project-url: ${{ inputs.project-url }}
    - name: Set reviewers (users)
      if: ${{ inputs.reviewers != '' }}
      uses: dannysauer/actions-assigner@v2.0.1
      with:
        reviewers: ${{ inputs.reviewers }}
        token: ${{ inputs.github-token }}
    - name: Set reviewers (teams)
      if: ${{ inputs.team-reviewers != '' }}
      uses: dannysauer/actions-assigner@v2.0.1
      with:
        team-reviewers: ${{ inputs.team-reviewers }}
        token: ${{ inputs.github-token }}
