query get_pull_requests_by_labels_and_state ($owner:String!,$repo:String!,$labels:[String!],$states:[PullRequestState!],$endCursor:String) {

  repository (name: $repo, owner: $owner) {
    pullRequests (
      after: $endCursor
      first: 100,
      labels: $labels,
      states: $states
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        timelineItems (itemTypes: LABELED_EVENT, last: 100) {
          nodes {
            ... on LabeledEvent {
              label {
                name
              }
              actor {
                login
              }
              createdAt
            }
          }
        }
        author {
          login
        }
        id
        headRefName
        number
      }
    }
  }

}
