query get_pull_requests_by_states_with_last_100_comments ($owner:String!,$repo:String!,$states:[PullRequestState!],$endCursor:String) {

  repository (name: $repo, owner: $owner) {
    pullRequests (
      after: $endCursor
      first: 1,
      orderBy: {
        field: UPDATED_AT
        direction: DESC
      }
      states: $states
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        comments (
          first: 100
          orderBy: {
            field: UPDATED_AT,
            direction: DESC
          }
        ) {
          nodes {
            body
            databaseId
          }
        }
        labels (first: 100) {
          nodes {
            id
            name
          }
        }
        number
        state
        title
      }
    }
  }

}
