---
name: Action lint

description: Linting for GitHub workflows

inputs:
  version:
    description: Actionlint version
    default: "1.7.3"
  ignore:
    description: Multiline; Ignore errors by messaging using regular expression.
  format:
    description: Format error messages using Go template
  custom-config-file:
    description: Actionlint custom configuration file path within original repo
  sanitize-runner-labels:
    description: Sanitize custom runner labels to only those supported by infra-team
    default: "true"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - run: echo "::add-matcher::${{ github.action_path }}/actionlint-matcher.json"
      shell: bash

    - name: Download actionlint
      id: get_actionlint
      env:
        ACTIONLINT_VERSION: ${{ inputs.version }}
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) $ACTIONLINT_VERSION
      shell: bash

    - name: Check workflow files
      env:
        FORMAT: ${{ inputs.format }}
        IGNORE_MESSAGES: ${{ inputs.ignore }}
        CUSTOM_CONFIG_FILE: ${{ inputs.custom-config-file }}
        DEFAULT_CONFIG_FILE: ${{ github.action_path }}/actionlint.yaml
        SANITIZE_CUSTOM_LABELS: ${{ inputs.sanitize-runner-labels }}
      run: |

        config_file="$DEFAULT_CONFIG_FILE"

        # Verify custom_runners contains only supported labels
        if [[ -n "$CUSTOM_CONFIG_FILE" ]]; then
          echo "Custom config provided: ${CUSTOM_CONFIG_FILE}"

          if [[ $SANITIZED_CONFIG_FILE != "false" ]]; then
          SANITIZED_CONFIG_FILE=/tmp/sanitized_custom_config_file.yaml
          ${{ github.action_path }}/sanitize-config.sh "$CUSTOM_CONFIG_FILE" "$DEFAULT_CONFIG_FILE" > "$SANITIZED_CONFIG_FILE"
            config_file="$SANITIZED_CONFIG_FILE"
          else
            config_file="$CUSTOM_CONFIG_FILE"
          fi
        fi

        # Combine all args into an array for running purposes and readability purposes
        _args=()
        _args+=(-color)

        # Set config file
        _args+=(-config-file "$config_file")

        # Exclude shellcheck and pyflakes
        _args+=(-shellcheck)
        _args+=(-pyflakes)

        # Ignore error messages
        if [[ -n "$IGNORE_MESSAGES" ]]; then
          while read -r line
          do
            _args+=(-ignore "$line")
          done < <($IGNORE_MESSAGES)
        fi

        # Set format for error messages
        if [[ -n "$FORMAT" ]]; then
          _args+=(-format "$FORMAT")
        fi

        echo "Running actionlint with these options:"
        echo "${_args[@]}"

        # Execute actionlint
        ${{ steps.get_actionlint.outputs.executable }} "${_args[@]}"

      shell: bash
