---
name: Action lint

description: Linting for GitHub workflows

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: camunda/infra-global-github-actions
        path: camunda-shared-actions
        sparse-checkout: |
          actionlint

    - name: Download actionlint
      id: get_actionlint
      run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      shell: bash

    - run: echo "::add-matcher::camunda-shared-actions/actionlint/config/actionlint-matcher.json"
      shell: bash

    - name: Check workflow files
      run: ${{ steps.get_actionlint.outputs.executable }} -color -config-file camunda-shared-actions/actionlint/config/actionlint.yaml
      shell: bash
