name: An action to test how to rerun jobs

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fail
      run: exit 1

  rerun-failed-jobs:
    needs: build
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: ${{ secrets.DEV_VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.DEV_VAULT_ROLE_ID }}
          secretId: ${{ secrets.DEV_VAULT_SECRET_ID }}
          exportEnv: false  # we rely on step outputs, no need for environment variables
          secrets: |
            secret/data/github.com/apps/retrigger-gha-workflow RETRIGGER_APP_KEY;
            secret/data/github.com/apps/retrigger-gha-workflow RETRIGGER_APP_ID; 

      - name: Generate a GitHub token
        id: github-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_ID }}
          private_key: ${{ steps.vault-secrets.outputs.RETRIGGER_APP_KEY }}

      - name: Retrigger run
        env:
          GH_DEBUG: api
        shell: bash
        run: |
          echo ${{ steps.github-token.outputs.token }} | gh auth login --with-token
          gh workflow run rerunfailedjob.yml -R camunda/infra-test-retrying-failed-actions --ref=main -F run_id=${{ inputs.run-id }} -F repository=${{ inputs.repository }} -F error_message=${{ inputs.error-message }}
