---
name: Add maintenance PRs to maintenance board

on:
  pull_request:
    types:
    - labeled

jobs:
  add-to-project:
    name: Add PR to maintenance project
    runs-on: ubuntu-latest
    steps:
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.4.3
      with:
        url: ${{ secrets.VAULT_ADDR }}
        method: approle
        roleId: ${{ secrets.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        exportEnv: false
        secrets: |
            secret/data/products/infra/ci/team-infrastructure GITHUB_APP_ID;
            secret/data/products/infra/ci/team-infrastructure GITHUB_APP_PRIVATE_KEY;
    - name: Generate token for GitHub
      id: generate-github-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ steps.secrets.outputs.GITHUB_APP_ID }}
        private_key: ${{ steps.secrets.outputs.GITHUB_APP_PRIVATE_KEY }}
    - uses: actions/add-to-project@v0.3.0
      with:
        project-url: https://github.com/orgs/camunda/projects/42/
        github-token: ${{ steps.generate-github-token.outputs.token }}
        labeled: dependency-upgrade
