---
name: pre-commit

on:
  pull_request:
    branches: ["**"]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.x"

      - uses: asdf-vm/actions/install@v4

      - run: |
          echo "::add-matcher::actionlint/actionlint-matcher.json"

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --verbose
