---
name: Test Dependency Vuln Check

on:
  pull_request:
    paths:
    - 'dependency-vuln-check/**'

jobs:
  test-dependency-vuln-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.x'
    - name: Install pytest
      run: pip install pytest
    - name: Run unit tests
      working-directory: dependency-vuln-check
      run: python -m pytest -q
