---
name: Use CI Nexus cache

description: Sets up use of co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml.

inputs:
  server-username:
    description: 'Nexus Username'
  server-password:
    description: 'Nexus Password'
  server-id:
    description: 'server ID'

runs:
  using: composite
  steps:
  - name: Create ~/.m2/settings.xml with cache configuration
    shell: bash
    run: |
      cat <<EOF > ~/.m2/settings.xml
      <?xml version="1.0" encoding="UTF-8"?>
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
        <interactiveMode>false</interactiveMode>
        <servers>
          <server>
            <id>${{ inputs.server-id }}</id>
            <username>${{ inputs.server-username }}</username>
            <password>${{ inputs.server-password }}</password>
          </server>
        </servers>
        <mirrors>
          <mirror>
            <id>${{ inputs.server-id }}</id>
            <mirrorOf>*</mirrorOf>
            <name>Camunda Nexus</name>
            <url>https://repository.nexus.camunda.cloud/content/groups/internal/</url>
          </mirror>
        </mirrors>
      </settings>
      EOF
